src/redux/actions/filter.js, src/views/Sidebar/Sidebar.js, src/views/UnitView/UnitView.js, src/views/UnitView/index.js, src/views/UnitView/styles.js
=> New UnitView for displaying unit information

src/components/MobileBottomNavigation/MobileBottomNavigation.js, src/components/MobileBottomNavigation/index.js
=> New MobileBottomNavigation component

src/views/Map/components/MapView.js
Add click event to marker to take user to unit details page
=> Add onclick event to unit markers

src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/views/HomeView/HomeView.js
Replace temporary data with info texts
=> Replace temporary data with info text

package-lock.json, package.json, server/server.js, src/App.js, src/client.js
Fix problem with conflicting class names caused by server side rendering generating separate class names. New solution removes old server styles before generating new jss class names on client side.
=> Fix jss styles loading conflict with server and client

src/redux/actions/user.js, src/redux/reducers/user.js, src/views/HomeView/HomeView.js, src/views/HomeView/index.js, src/views/Map/MapContainer.js, src/views/SearchView/SearchView.js, src/views/SearchView/index.js, src/views/Service/ServiceView.js
* Add "current page" -field to user state to tell the map which markers to draw.
=> Show correct markers on map depending on page

src/themes/index.js, src/utils/unitHelper.js
* Add the new primary blue color for the app
* Change default berry color to blue temporarily
=> Color changes

src/App.js, src/layouts/DefaultLayout.js
Reload page on language change to ignore problems with components not updating and easier HEAD attribute changes.
=> Reload page on same location on language change

src/browserTests/accessibilityTest.js, src/browserTests/unitPageTest.js, src/components/ListItems/ServiceItem/ServiceItem.js, src/components/ListItems/SimpleListItem/SimpleListItem.js, src/redux/actions/selectedUnit.js, src/views/Map/components/MapView.js
* Add browser tests for unitView
* Add automatic axe tests to all pages
=> Add tests, small fixes

src/views/SearchView/SearchView.js
* Update search query param with previous search on SearchView's componentDidMount.
=> Replace search query in URL on SearchView componentDidMount

src/views/SearchView/SearchView.js
* Redirect user forward if only 1 result is found
=> Redirect on single search result

README.md, package-lock.json, src/views/HomeView/HomeView.js
Added development greetings for May with HTML linebreaks.
=> Development greetings 14.5.2019

src/components/SearchBar/SearchBar.js, src/views/HomeView/HomeView.js, src/views/MobileMapView/MobileMapView.js, src/views/SearchView/SearchView.js
Refactoring search submit functionality to SearchBar component.
=> Move search submit functionality to SearchBar

server/server.js
Change html language attribute based on language parameter of URL in request
=> Set locale to html-tag on server

src/components/ListItems/ServiceItem/ServiceItem.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/Services.js
On school units, list services with periodical data differently than normal services.
=> Add different list for school unit services

src/themes/index.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/AccessibilityInfo/AccessibilityInfo.js, src/views/UnitView/components/AccessibilityInfo/index.js, src/views/UnitView/components/AccessibilityInfo/styles.js
New AccessibilityInfo component that lists accessibility problems related to unit and specific shortcomings based on user's accessibility settings.
=> New AccessibilityInfo component for UnitView

src/views/EventDetailView/EventDetailView.js
Changed EventDetailView to use selectedUnit rather than event's location. Data seems mostly correct but telephone is actually phone in data coming from ServiceMap API.
=> Fetch and use selected unit's data in event defails

src/components/TopBar/TopBar.js
Updated the top menu settings icon to the newer version of the Material Accessibility icon.
=> Updated accessibility icon

src/layouts/DefaultLayout.js, src/layouts/index.js, src/redux/actions/user.js, src/redux/reducers/user.js, src/views/AddressView/AddressView.js, src/views/AddressView/components/DistrictItem.js, src/views/AddressView/index.js
* Remove mobile check
* Add new component DistrictItem to AddressView that handles mobile/desktop state
=> Remove mobile state form redux. Add new component

src/views/UnitView/UnitView.js
* Add isFetching to unitView so that Loading text can be displayed during fetch
=> Fix loading text

src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/ServiceItem/ServiceItem.js, src/views/UnitView/components/ContactInfo.js, src/views/UnitView/components/Events.js, src/views/UnitView/components/Reservations.js, src/views/UnitView/components/Services.js
+ Add check to unitView lists that define if divider is needed (last item on the list should not display divider)
+ Fix issue with units with null contact info displaying empty list
+ Refactor school period service listing
=> Check if divider needed on unitView lists

src/views/SearchView/SearchView.js
- Fix SearchBar component not showing when search is empty
=> Show search bar on search result page with no results

config/default.js, src/components/Settings/styles.js, src/components/TopBar/styles.js, src/layouts/DefaultLayout.js, src/views/Map/MapContainer.js
Refactoring topbar height to config file
=> Move topbar height to config file

config/default.js, webpack.config.js
Fix environment defaults to avoid warnings on webpack build
=> Fix environment defaults to avoid warnings on webpack build

src/redux/actions/unit.js
Fix search history not saving on search fetch success
=> Fix search history saving on search fetch success

src/components/Lists/ResultList/ResultList.js, src/components/Lists/ResultList/styles.js
Fix ResultList title vertical alignment
=> Fix ResultList title vertical alignment

src/views/EventDetailView/EventDetailView.js, src/views/UnitView/styles/styles.js
Change image height and add cropping to fit the area
=> Change image styles

src/components/Settings/Settings.js, src/components/Settings/SettingsTitle.js
Add group role to checkbox settings
=> Add group role to checkbox settings

src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/UnitItem/UnitItem.js, src/utils/fetch/constants.js
Change UnitItem 'unit' text to show contract type instead
=> Change UnitItem 'unit' text to show contract type

src/redux/actions/unit.js
Fix search not utilizing current locale in fetch
=> Fix search not utilizing current locale in fetch

src/components/TitleBar/styles.js
Fix TitleBar long tile breaking layout
=> Fix TitleBar long tile breaking layout

src/redux/actions/selectedUnit.js, src/views/EventDetailView/EventDetailView.js, src/views/MapView/MapView.js
Show unit marker on map in event view
=> Show unit marker on map in event view

src/redux/reducers/address.js, src/views/AddressView/AddressView.js, src/views/MapView/MapView.js, src/views/MapView/components/AddressMarker.js, src/views/MapView/components/AddressPopup.js, src/views/MapView/components/UnitMarkers.js
- Remove unneeded address states and rename clickCoordinates -> addressCoordinates
- Remove duplicate components from map render
=> fix issues from previous merges

src/views/UnitView/UnitView.js, src/views/UnitView/components/ContactInfo.js, src/views/UnitView/components/ElectronicServices.js, src/views/UnitView/components/Events.js, src/views/UnitView/components/Reservations.js, src/views/UnitView/components/Services.js
- Fix heading levels in UnitView
- Remove unused render code in UnitView
=> Fix heading levels and clean unused code from UnitView

src/components/SearchBar/components/SuggestionBox.js, src/components/SearchBar/createSuggestions.js, src/components/SearchBar/expandSearch.js
* Use new search suggestions fetch
=> Add first version of new search functionality

src/redux/actions/unit.js
Previously only one address result was displayed (other addresses were eliminated as duplicates)
=> Fix missing address results

src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/ResultItem/styles.js
Show ResultItem distance text on right side of title on small screen widths
=> Show ResultItem distance text on right side of title on small screen widths

src/components/Settings/Settings.js, src/components/Settings/SettingsTitle.js, src/components/Settings/styles.js, src/components/TopBar/TopBar.js, src/components/TopBar/index.js, src/components/TopBar/styles.js, src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/layouts/DefaultLayout.js, src/redux/reducers/simpleReducers.js, src/views/HomeView/HomeView.js
* New individual settings pages for each setting type
* New styles to settings pages
* New settings buttons to top bar
=> Add new settings page and settings buttons

server/server.js
=> Fix issue with font style on safari browser

src/components/TopBar/TopBar.js, src/components/TopBar/styles.js
* Fix styles
* Make logo clickable
=> Fix incorrect top bar styles

src/views/AddressView/AddressView.js, src/views/AddressView/styles.js
+ also comment out some code that is unused at this point
=> Fix address view stylings

src/components/TabLists/TabLists.js, src/views/SearchView/SearchView.js
Show expanded search only for units tab
=> Show expanded search only for units tab

src/components/ListItems/UnitItem/UnitItem.js, src/components/ListItems/UnitItem/index.js
Calculate unit distance from address if possible
=> Calculate unit distance from address if possible

src/components/TopBar/styles.js
Previously button was partially out of view
=> Fix top bar button issue on tablet view

src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/views/UnitView/components/AccessibilityInfo/AccessibilityInfo.js, src/views/UnitView/components/AccessibilityInfo/styles.js
- Fix AccessibilityInfo component's stylings
- Change icon colors to use primary
=> Fix AccessibilityInfo stylings

src/client.js, src/components/TopBar/TopBar.js, src/redux/actions/user.js, src/utils/ThemeWrapper.js
- Changed contrast change functionality to work without reloading page by utilizing redux
=> Make contrast change without reloading page

src/components/ListItems/SuggestionItem/SuggestionItem.js
Move onclick handlers and add keyboardHandler check
=> Move onClick handlers from span to list item

src/components/DrawerMenu/DrawerMenu.js
Disable active styles from drawer menu for now, until issues with icons' active color that cause problems are fixed
=> Disable active styles from drawer menu

src/components/TabLists/TabLists.js, src/views/UnitView/UnitView.js
* NOTE: also temporarily disabled min height for tabs, since it caused some issues.
=> Add wrapper div to fix layout issues with safari

src/components/ListItems/AddressItem/AddressItem.js, src/components/ListItems/SimpleListItem/SimpleListItem.js, src/components/SearchBar/SearchBar.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js
Fix suggestion list arrow key browsing with added address items
=> Add suggestion class to address suggestions

src/components/TopBar/styles.js, src/layouts/DefaultLayout.js, src/views/MapView/MapView.js
Since expanded suggestion box does not work on mobile map view, remove it for now
=> Fix mobile map height. Remove search bar from map

src/components/SearchBar/createSuggestions.js, src/views/AddressView/AddressView.js, src/views/AddressView/utils/fetchAddressData.js
Change address url data to correct data on when address language doesn't represent current language
=> Change address data fetching to fetch data from address endpoint

src/components/Settings/Settings.js, src/components/Settings/index.js
* If user changes colorblind setting OR visually impaired setting on: change theme to high contrast. IF user has not made changes to map settings at the same time, also change map to high contrast.
* If user changes colourblind setting OR visually impaired setting off AND both of the settings are off: change theme to default. IF user has not made changes to map settings at the same time, also change map to default.
=> Add changing of map based on settings

config/default.js, src/components/ListItems/AddressItem/AddressItem.js, src/components/ListItems/AddressItem/index.js, src/components/TopBar/TopBar.js, src/components/TopBar/index.js, src/utils/address.js, src/views/AddressView/AddressView.js, src/views/AddressView/index.js, src/views/AddressView/utils/fetchAddressData.js, src/views/AddressView/utils/fetchDistricts.js, src/views/HomeView/HomeView.js, src/views/HomeView/index.js, src/views/MapView/MapView.js, src/views/MapView/components/AddressPopup.js, src/views/MapView/index.js, src/views/SearchView/SearchView.js, src/views/SearchView/index.js
Fix handling of street names in different languages.
=> Release v1.0.5

src/redux/actions/address.js, src/redux/reducers/address.js, src/views/AddressView/AddressView.js, src/views/AddressView/index.js, src/views/MapView/components/AddressMarker.js
Moved address data to redux. Fixed issue with address tooltip not showing address text
=> Move address data to redux and fix tooltip

src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/views/MapView/config/mapConfig.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/UnitLinks.js
* Added unit web-links to unit page
=> Release v1.0.8

src/components/SettingsInfo/SettingsInfo.js, src/components/SettingsInfo/styles.js
* Use button component so that key presses are handled properly
* Remove h3 from settings link, since there is already a h3 before it
=> Fix search page settings link accessibility

src/components/Settings/Settings.js, src/components/Settings/styles.js
Removed snackbar button to help with issue where users try to close settings view with snackbar close button.
=> Remove snackbar button

src/views/UnitView/utils/unitSectionFilter.js
Fixes unworking unit details page for some units
=> Ignore missing item names in unitSectionFilter

server/legacyRedirector.js
These bugs caused some 500s in production.
=> Fix url handling in legacy redirector and fix API url configuration

src/views/AddressView/AddressView.js, src/views/AddressView/utils/fetchDistricts.js
Move area tab first, and move health districts to top in area tab
=> Change address page tab and area order

src/views/ServiceTreeView/ServiceTreeView.js
* Accessibility: added indeterminate value to checkboxes
* Fix issue where node wouldn't be selected if all child nodes are selected
=> Service tree accessibility

src/views/UnitView/utils/unitSectionFilter.js
Connections with same name but different data were not shown.
=> Remove duplicate check for connections

src/views/MapView/utils/unitMarkers.js, src/views/UnitView/components/ContactInfo.js
Fix handling of missing unit coordinates.
=> Release v1.0.18

src/components/TabLists/styles.js
- Add better contrast for tab element keyboard focus
=> Tab element better keyboard focus contrast

src/components/TabLists/TabLists.js
Add tabpanel role and controls to match WCAG standards.
=> Add tabpanel role and tab controls

src/redux/actions/user.js
- Make accuracy limit stricter 
- Add enableHighAccuracy option to geolocation
=> User location accuracy

src/components/SearchBar/createSuggestions.js
Note! Not to be merged until 2020-03-06, when which the search reindexing has been completed.
=> Start using final production API URL for suggestions

src/components/SearchBar/createSuggestions.js, src/i18n/translations/sv.js
- Start using final production API URL for suggestions
=> Release v1.0.21

src/views/SearchView/SearchView.js
- Inspect future props for redirect isFetching value
- Clean up unused state values
=> Fix search fetch in cases where redirect fetch gets an error

src/components/AlertBox/AlertBox.js, src/components/AlertBox/index.js, src/components/AlertBox/styles.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/layouts/DefaultLayout.js
Add alert box component to display messages to user. This is a temporary implementation, with hard-coded message.
=> Add temporary alert box component

src/views/UnitView/UnitView.js
- Fix missing contract type id error
=> Release v1.0.24

browserTests/searchTest.js, src/components/ExpandedSuggestions/ExpandedSuggestions.js, src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/SuggestionItem/SuggestionItem.js, src/components/SearchBar/PreviousSearches.js, src/components/SearchBar/SearchBar.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/redux/actions/user.js
Add navigation tests for search suggestions
Add regression test for search view
=> New regression tests for search view

src/components/AlertBox/AlertBox.js, src/layouts/DefaultLayout.js
Make AlertBox not to have defaults by moving default content to DefaultLayout and pass them as props.
=> Refactor AlertBox to have no default content

src/components/DescriptionText/DescriptionText.js, src/components/DescriptionText/index.js, src/views/EventDetailView/EventDetailView.js, src/views/UnitView/components/Description/Description.js
Change titleComponent to required to avoid accessibility problems with default headings
Change title proptype to node
=> Refactoring DescriptionText

src/components/DesktopComponent/DesktopComponent.js, src/components/ExpandedSuggestions/ExpandedSuggestions.js, src/components/ListItems/SuggestionItem/SuggestionItem.js, src/components/MobileComponent/MobileComponent.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/components/TabLists/TabLists.js, src/components/TitleBar/TitleBar.js, src/components/TitleBar/styles.js, src/layouts/DefaultLayout.js, src/utils/isMobile.js, src/views/AddressView/AddressView.js, src/views/AddressView/styles.js, src/views/EventDetailView/EventDetailView.js, src/views/InfoView/InfoView.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/ExtendedData/ExtendedData.js, src/views/UnitView/styles/styles.js
**Make TitleBar component sticky on most of the pages**
- Update TitleBar component so that the component itself contains the sticky styles.
- Add new hook _useMobileStatus_  which makes mobile layout check easier
- Update TabList component sticky calculations
=> Correct sticky styles to title bar

src/layouts/DefaultLayout.js, src/layouts/index.js, src/layouts/styles.js
Fix conflict issue with AlertBox and new global link styling
=> Fix alertbox link stylings

src/components/TabLists/TabLists.js, src/views/UnitView/UnitView.js
Minimizing screen on embed unit view caused page to crash
=> Remove style calculations from embed unti view

src/components/TabLists/TabLists.js, src/views/UnitView/UnitView.js
Hotfix
* Fix embed window scaling crash
=> Release v1.0.26

.travis.yml
=> Fix failing travis build

src/components/Settings/index.js, src/components/TopBar/index.js, src/layouts/DefaultLayout.js, src/layouts/index.js, src/redux/actions/settings.js
- Move toggleSettings logic to action and inject directly to  Settings and TopBar
=> Refactor settings component

browserTests/searchTest.js, src/views/SearchView/SearchView.js
Add accessibility tests for tabs, search live element, and SettingsInfo element
=> Search view regression tests

browserTests/browserTest.js, browserTests/homeTest.js, src/components/PaperButton/__testCafe__/PaperButton.tc.js, src/components/SearchBar/SearchBar.js, themes/index.js
=> Update browser test for language change

src/components/Navigator/Navigator.js, src/components/TopBar/TopBar.js, src/layouts/DefaultLayout.js, src/views/MapView/MapView.js
spMap would incorrectly pick "map=true" param as map type, when mobile map is open and map type is changed.
=> Fix map search param on mobile map change

src/redux/selectors/ordering.js, src/views/SearchView/SearchView.js
Also enable result ordering on address tab, since it seems to be working well.
=> Fix address result ordering bug

config/default.js, server/server.js
Default to Helsinki area if no env variable for the position is set.
=> Enable using env variable for initial map position

browserTests/areaTest.js, browserTests/searchTest.js, src/components/ListItems/SuggestionItem/__tests__/SuggestionItem.test.js, src/components/ListItems/SuggestionItem/__tests__/__snapshots__/SuggestionItem.test.js.snap, src/components/PaginationComponent/__tests__/PageElement.test.js, src/components/PaginationComponent/__tests__/PaginationComponent.test.js, src/components/PaginationComponent/__tests__/__snapshots__/PageElement.test.js.snap, src/components/PaginationComponent/__tests__/__snapshots__/PaginationComponent.test.js.snap, src/components/ServiceMapButton/__tests__/ServiceMapButton.test.js, src/components/ServiceMapButton/__tests__/__snapshots__/ServiceMapButton.test.js.snap
Use English as locale for tests, because Finnish language is not working on updated rect-intl
=> Update jest tests

browserTests/accessibilityTest.js, browserTests/componentContrastTest.js, browserTests/focusIndicatorTest.js, src/components/ListItems/ResultItem/__tests__/__snapshots__/ResultItem.test.js.snap, src/components/ListItems/SimpleListItem/__tests__/__snapshots__/SimpleListItem.test.js.snap, src/components/ListItems/SuggestionItem/__tests__/__snapshots__/SuggestionItem.test.js.snap, src/components/PaginationComponent/__tests__/__snapshots__/PageElement.test.js.snap, src/components/PaginationComponent/__tests__/__snapshots__/PaginationComponent.test.js.snap, src/components/ServiceMapButton/__tests__/__snapshots__/ServiceMapButton.test.js.snap, src/utils/componentContrast.js, themes/index.js
Add component contrast checking test. Use the test to check SMButton and BackButton components on each page
=> Component contrast test

browserTests/accessibilityTest.js, src/views/ServiceTreeView/ServiceTreeView.js
- Add accessibility tests to service tree view
- Fix accessibility errors
=> Add service tree view axe tests

src/components/ListItems/DivisionItem/DivisionItem.js, src/views/AreaView/AreaView.js
Temporary implementation for hiding previous school period data. Changes will be made later to the backend which gives this data.
=> Remove old school years

config/default.js, server/server.js, src/utils/settings.js, src/views/HomeView/HomeView.js
- Add configurable settings for map options
- Add configurable settings for old map link
=> Turku Update: Add configurable settings for City of Turku

.env.example, .travis.yml, config/default.js, server/server.js, src/components/SMIcon/index.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/components/Settings/Settings.js, src/components/Settings/index.js, src/components/SettingsInfo/SettingsInfo.js, src/components/TopBar/TopBar.js, src/redux/actions/settings.js, src/redux/reducers/settings.js, src/redux/rootReducer.js, src/redux/selectors/results.js, src/redux/selectors/service.js, src/utils/settings.js, src/views/ServiceTreeView/ServiceTreeView.js
Changes city selection to dynamic.
=> Dynamic city selection

src/components/Settings/Settings.js
Settings radio values were not displayed.
=> Fix broken settings

src/views/MapView/components/DistanceMeasure/DistanceMeasure.js, src/views/MapView/styles.js
Improves measuring tool accessibility on high contrast map and aerial image map.
=> Add borders to measuring tool markers and lines

config/default.js, server/server.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/AddressView/AddressView.js, src/views/FeedbackView/FeedbackView.js, src/views/HomeView/HomeView.js, src/views/UnitView/UnitView.js
Add dynamic settings for: 
- External translations
- Show/Hide area selection and nearby services
- Link to additional feedback info
- Show/Hide read speaker button in unit view
=> Add other dynamic settings 

src/components/DropDownMenuButton/styles.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js
Add more informative text to help keyboard users. Modify menu item styles to work with multiline text.
=> Add additional text to measuring tool menu item

.babelrc, src/views/DivisionView/DivisionView.js
- Fix broken search bar clear button
- Fix unintended marker zooming
=> Release v1.1.1

src/views/AreaView/AreaView.js, src/views/AreaView/components/AreaTab/AreaTab.js
Improve district period data handling. Fix broken years on area view DistrictItem-components
=> Refactor district period data handling

browserTests/mapTest.js, src/views/MapView/MapView.js, src/views/MapView/components/MarkerCluster/MarkerCluster.js
New separate `unitGeometry` variable to `MapView` that is changed when `highlightedUnit` or `currentPage` changes.
=> Fix unit geometry drawing to show when highlighted unit selected

client/client.js, config/default.js, package-lock.json, package.json, server/server.js
=> Add sentry client side handling

src/views/MapView/components/MarkerCluster/MarkerCluster.js, src/views/MapView/components/MarkerCluster/clusterUtils.js
Fixed popup not showing when selecting location from list rather than map. Need to figure out if popup should disappear when coming back from UnitView to SearchView
=> Fix highlight popup not showing when selected from list

server/dataFetcher.js, src/redux/actions/selectedUnitHearingMaps.js, src/utils/fetch/constants.js, src/views/UnitView/UnitView.js
Fetch hearing maps only if unit has "kuuluvuuskartta" in keywords.
=> Add condition to hearing map fetch.

src/views/UnitView/components/ContactInfo/ContactInfo.js, src/views/UnitView/styles/styles.js
Unit call charge information used wrong divider length
=> Fix wrong divider on call charge info

src/views/AreaView/AreaView.js
- Add another fetch reducer (unitsFetching) for geographical district unit fetch, to prevent multiple unit fetches.
- Rename district fetch reducer from "fetching" to "ditsrictsFetching".
=> Fix area view multiple district unit fetch issue

src/views/MapView/MapView.js, src/views/MapView/components/UnitGeometry/UnitGeometry.js
Draw MultiPolygon geometry for highlighted unit. Can be tested by searching "ulkoilusaaret" and selecting "Vasikkasaari..."
There's still a question if we want to show Polygons and Polylines in search for all units. But I think we can forward this one and add that later on if it's still required.
=> Change UnitGeometry to show MultiPolygon data

src/components/TabLists/TabLists.js
Default tabIndex to 0 if tabIndex is out of bound
=> Add try-catch when accessing filterData with index

src/views/MapView/MapView.js, src/views/MapView/components/UnitGeometry/UnitGeometry.js, src/views/MapView/components/UnitGeometry/index.js
Add onclick event for unit polygon.
=> Add onclick event for unit polygon

src/components/ListItems/AddressItem/AddressItem.js, src/components/ListItems/DivisionItem/DivisionItem.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/utils/address.js, src/views/AddressView/utils/fetchAdministrativeDistricts.js, src/views/AreaView/AreaView.js, src/views/AreaView/components/UnitTab/UnitTab.js, src/views/MapView/components/MarkerCluster/MarkerCluster.js, src/views/MapView/components/MarkerCluster/clusterUtils.js, src/views/UnitView/components/ContactInfo/ContactInfo.js
Added postal code to getAddressText function in address utility.
Added postal code to ContactInfo field
=> Add postal code to unit contact info and address text utility

src/assets/icons/CoordinateMarker.svg, src/assets/icons/CoordinateMarkerContrast.svg, src/components/SMIcon/index.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/utils/coordinate.js, src/views/MapView/MapView.js, src/views/MapView/components/AddressPopup/AddressPopup.js, src/views/MapView/components/CoordinateMarker/CoordinateMarker.js, src/views/MapView/components/CoordinateMarker/index.js, src/views/MapView/styles.js, src/views/ServiceView/ServiceView.js, src/views/ServiceView/index.js
Add coordinate selection to AddressPopup
=> Add coordinate marker based on URL parameters

src/views/ServiceTreeView/ServiceTreeView.js
- Added focus to title after removing all selections
- Added focus to previous or next elements on selection list
=> Fix service tree selection remove focus problem

src/components/ListItems/DivisionItem/DivisionItem.js, src/components/TopBar/TopBar.js
- Contrast button from link to button
- Division item from button to link
=> Clickable element roles

src/components/BackButton/BackButton.js, src/components/DropDownMenuButton/DropDownMenuButton.js, src/components/Navigator/Navigator.js, src/components/ToolMenu/ToolMenu.js, src/redux/actions/breadcrumb.js, src/views/PrintView/PrintView.js
- Fix focus to Toolmenu when coming back from PrintView
- Fix focus to ToolMenu when coming back from embedder
- New breadcrumb functionality with saved focusTarget data in order to refocus back to specific element when coming back with navigator
=> Fix focus to ToolMenu when coming back from PrintView

config/paths.js, src/redux/actions/breadcrumb.js, src/views/HomeView/HomeView.js, src/views/InfoView/InfoView.js
- Fixed focus issue with InfoView
=> Add focus to viewTitle on info view page change

config/default.js
=> Disable ortographic map

src/redux/selectors/results.js, src/utils/filters.js
Searching for Espoo districts (such as Bodom or Espoonkartano) caused crash on search page.
=> Remove areas from search results

.dockerignore, Dockerfile, docker-compose.yml
=> Update node from v10 to v14

src/components/TabLists/TabLists.js, src/views/AreaView/components/AreaTab/AreaTab.js
- Render inactive tab to improve tab change performance
- Memoize area view list items to reduce number of re-renders
=> Improve area view performance

src/themes/index.js, src/views/MapView/MapView.js, src/views/MapView/components/DistanceMeasure/DistanceMeasure.js, src/views/MapView/styles.js
Remove map optimisation that prevented measuring tool styles.
=> Fix measuring tool style

src/components/SearchBar/previousSearchData.js
New previousSearch functionality based on timestamps weighted with search count.
Change search times based solution to time based solution with weights from search counts. Weights are reduced every 5 days if user uses search.
=> New previousSearch functionality

src/components/ListItems/UnitItem/UnitItem.js, src/utils/fetch/constants.js, src/utils/unitHelper.js, src/views/UnitView/UnitView.js
Added municipality text next to contract type text.
=> Unit contract type municipality

src/views/EmbedderView/EmbedderView.js, src/views/EmbedderView/components/EmbedController.js, src/views/EmbedderView/index.js, src/views/EmbedderView/utils/utils.js
Changed embedder city setting to use checkboxes instead of radio buttons. Use settings as default for city selection.
=> Change embedder city settings to reflect settings and use checkboxes

src/views/MapView/utils/mapUtility.js
FIxed unit focusing to handle unit geometry on MultiPolygon data
=> Fixed unit focus to adjust to MultiPolygon geometry

browserTests/searchTest.js, src/components/Lists/PaginatedList/PaginatedList.js
Add browser test to ensure default page functionality is tested
=> Fix paginated lists search parameter page handling

src/views/MapView/components/Districts/Districts.js, src/views/UnitView/components/Highlights/Highlights.js
- Disable area view popup link if no env-value provided
- Fix wrong env check on outdoor exercise url
=> Disable some features if no env-value provided

client/client.js
Added some of the most common TypeErrors to Sentry's ignore list
=> Add common fetch related TypeErrors to Sentry's ignore list

server/externalScripts.js, server/ieMiddleware.js, server/server.js
Added cookiehub code based on environment variable. This is done because different cookiehub url is meant for specific domain but servicemap is used in 3 different domains currently
=> Add cookiehub code handling based on environment variables

src/components/Navigator/Navigator.js, src/layouts/components/ViewRouter/ViewRouter.js, src/views/FeedbackView/FeedbackView.js, src/views/UnitView/UnitView.js
Fix feedback back button functionality to take user back to unit view
=> Change unit feedback to use router

src/components/ListItems/DivisionItem/DivisionItem.js, src/views/AreaView/components/DistrictUnitList/DistrictUnitList.js, src/views/MapView/components/Districts/Districts.js
Added division number (origin id) to protection districts.
=> Add division id to protection division names

src/components/AddressSearchBar/AddressSearchBar.js
- [#630](https://github.com/City-of-Helsinki/servicemap-ui/pull/630) Fix address search bar results
=> Release v1.2.1

src/views/MapView/components/Districts/Districts.js
Changes:
- [#633] (https://github.com/City-of-Helsinki/servicemap-ui/pull/633) Fix nature area links
=> Release v1.2.2

src/views/MapView/MapView.js, src/views/MapView/components/PanControl/PanControl.js, src/views/MapView/components/PanControl/index.js, src/views/MapView/components/PanControl/styles.js, src/views/MapView/styles.js, src/views/MapView/utils/index.js
New PanControl component for handling map panning with keyboard.
~Still need to add direct keyboard handling for moving map with arrow keys.~ Added in 058ef1e
=> New PanControl component for panning leaflet map

src/views/UnitView/components/Services/Services.js
Changed Service component from class component to function component. This seems to fix the issue.
=> Fix unit services tab showing previous unit services

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/layouts/components/PageHandler/PageHandler.js, src/layouts/components/PageHandler/index.js, src/layouts/components/PageHandler/pageDescriptions.js, src/layouts/components/ViewRouter/ViewRouter.js, src/views/UnitView/components/InfoList/InfoList.js
Created description texts that will be shown on google results
=> Page seo descriptions

src/views/MapView/components/MarkerCluster/clusterUtils.js
Change unit popup distance position
=> Move unit popup distance to new line

azure-pipelines-master.yml, azure-pipelines-release.yml
These pipelines extend the base pipeline and defines CI and PR triggers in GitHub
=> Added Azure DevOps pipelines

src/i18n/en.js, src/i18n/fi.js
=> Change finnish and english texts for search result jump link

browserTests/focusIndicatorTest.js, src/index.css, src/redux/actions/user.js, src/themes/index.js
Fix breaking focus indicator test by removing button transition animation
Additionally fix map attribution background color contrast
=> Fix breaking focus indicator test

src/layouts/components/ViewRouter/ViewRouter.js
From accessibility report section 3.5
=> Add missing page titles

src/components/PaperButton/PaperButton.js, src/views/HomeView/HomeView.js
=> Add opens on new tab info to old servicemap link

src/views/EmbedderView/EmbedderView.js
=> Add aria-label for copy url field

src/components/ErrorBoundary/ErrorBoundary.js, src/components/ErrorBoundary/ErrorComponent.js, src/components/ErrorBoundary/ErrorTrigger.js, src/components/ErrorBoundary/index.js, src/components/ErrorBoundary/styles.js, src/components/Logos/HomeLogo/index.js, src/components/TopBar/TopBar.js, src/components/index.js, src/context/ErrorContext.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/layouts/DefaultLayout.js, src/layouts/components/ViewRouter/ViewRouter.js, src/utils/user.js
New ErrorBoundary component for handling error rendering.
=> New ErrorBoundary component

config/default.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/UnitLinks/UnitLinks.js
=> Filter duplicate feedback links

src/views/FeedbackView/FeedbackView.js
=> Use correct aria-attribute on form

src/views/MapView/components/TransitStops/TransitStopInfo/TransitStopInfo.js, src/views/MapView/components/TransitStops/TransitStops.js
=> Remove transit popups from screen readers

src/views/MapView/components/Districts/Districts.js
Added new high contrast mode area borders to area view
=> Add high contrast area borders

src/views/MapView/components/EntranceMarker/EntranceMarker.js
Also increased radius in which entrance will be hidden
=> Check entrances without location.

browserTests/accessibilityTest.js, src/components/DescriptionText/DescriptionText.js
=> Fix event view test

src/views/UnitView/UnitView.js
Feedback button was hidden from private services. Added it back
=> Disable feedback form hiding

browserTests/addressTest.js
Testing fix for address view browser test
=> Fix address test UnitItem not being found

src/redux/actions/unit.js, src/views/MapView/index.js, src/views/MapView/utils/transitFetch.js
Add several null checks to fix errors found by sentry
=> Fix some errors found by sentry

browserTests/areaTest.js, src/views/AreaView/components/DistrictToggleButton/DistrictToggleButton.js, src/views/AreaView/components/DistrictUnitList/DistrictUnitList.js, src/views/AreaView/components/ServiceTab/ServiceTab.js
Enable and fix previously broken area view tests
=> Add tests to area view

package-lock.json, package.json
[Use quarantine mode on tests](https://testcafe.io/documentation/402830/guides/basic-guides/run-tests#quarantine-mode). This mode repeats failing test n times if it fails. This should help with unstable tests that fail for no reason and need to be restarted. Quarantine mode configured to attempt failing tests 5 times and to require at least 2 successes to approve.
Updated test libraries for this feature.
=> Update test libraries. Add quarantine mode

src/views/UnitView/UnitView.js, src/views/UnitView/components/UnitDataList/UnitDataList.js, src/views/UnitView/components/UnitsServicesList/UnitsServicesList.js
- Unit view service tab events and reservations lists didn't have information about the full amount of items. Changed data prop to include max data and used it to define if button should be present.
=> Fix unit data list missing show more buttons

.github/workflows/ci.yml
Update GHA-tests naming. Use also master-branch.
=> Update GHA-tests rules

.github/workflows/analyze-code.yml, sonar-project.properties
=> Add SonarCloud configuration

src/components/AddressSearchBar/AddressSearchBar.js
Pressing enter on address bar with an address already selected cleared the address bar.
=> Fix address bar enter click

src/views/InfoView/InfoView.js
=> Update accessibility info text

browserTests/searchTest.js, browserTests/serviceTest.js, server/legacyRedirector.js, server/server.js, src/components/AddressSearchBar/AddressSearchBar.js, src/components/ResultOrderer/ResultOrderer.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/components/SearchBar/createSuggestions.js, src/components/SearchBar/previousSearchData.js, src/components/ToolMenu/ToolMenu.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/redux/reducers/simpleReducers.js, src/utils/tracking.js, src/utils/useLocaleText.js, src/views/AddressView/AddressView.js, src/views/AreaView/AreaView.js, src/views/EmbedderView/EmbedderView.js, src/views/EmbedderView/components/EmbedHTML.js, src/views/EmbedderView/components/IFramePreview.js, src/views/EmbedderView/utils/utils.js, src/views/FeedbackView/FeedbackView.js, src/views/InfoView/InfoView.js, src/views/MapView/MapView.js, src/views/MapView/utils/mapActions.js
- [#753](https://github.com/City-of-Helsinki/servicemap-ui/pull/753) New box option for embedder tool
- [#752](https://github.com/City-of-Helsinki/servicemap-ui/pull/752) Updated search suggestions
- [#750](https://github.com/City-of-Helsinki/servicemap-ui/pull/750) Fixed address search bar enter press bug
- [#749](https://github.com/City-of-Helsinki/servicemap-ui/pull/749) Updated accessibility statement
=> Release v1.2.19

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/PriceInfo/PriceInfo.js, src/views/UnitView/components/PriceInfo/index.js
- [#757](https://github.com/City-of-Helsinki/servicemap-ui/pull/757) Added new unit charge information component
=> Release v1.2.21

src/components/TitleBar/TitleBar.js, src/utils/settings.js
- Fixed unit link sharing missing translation
=> Fix accessibility link null translation

src/components/Lists/TitledList/styles.js, src/views/UnitView/components/UnitsServicesList/UnitsServicesList.js
=> Remove duplicate services

src/components/Lists/TitledList/TitledList.js, src/views/UnitView/UnitView.js
Unit events list moved to first tab
=> Move unit events to first tab

.env.example, config/default.js, server/server.js, src/components/Navigator/Navigator.js, src/views/SearchView/SearchView.js, src/views/SearchView/index.js
- Added custom dimension to Matomo that logs search queries with no results
=> Send searches with no results to matomo

src/components/Dialog/AcceptSettingsDialog/AcceptSettingsDialogComponent.js, src/utils/settings.js
Bug prevented saving mobility settings to none.
=> Fix mobility setting bug

src/components/SearchBar/SearchBarComponent.js, src/views/SearchView/SearchView.js
- Added option for embedding multiple units using unit ids.
=> Release v1.2.26

src/components/ListItems/DivisionItem/DivisionItem.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/redux/actions/district.js, src/views/AreaView/components/DistrictUnitList/DistrictUnitList.js, src/views/AreaView/utils/districtDataHelper.js, src/views/MapView/components/Districts/Districts.js
- [#787 ](https://github.com/City-of-Helsinki/servicemap-ui/pull/787) Updated area view data handling
=> Release v1.2.28

src/hsl-icons.css, src/views/MapView/components/TransitStops/TransitStopInfo/TransitStopInfo.js, src/views/MapView/components/TransitStops/TransitStops.js, src/views/MapView/styles.js, src/views/MapView/utils/transitFetch.js
- Added HSL bike stations to map as transit stop.
=> Add bike stations to map

config/paths.js, src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/ResultItem/__tests__/__snapshots__/ResultItem.test.js.snap, src/components/ListItems/ResultItem/styles.js, src/components/ListItems/UnitItem/UnitItem.js, src/components/Lists/PaginatedList/PaginatedList.js, src/components/Lists/ResultList/ResultList.js, src/components/Lists/ResultList/__tests__/__snapshots__/ResultList.test.js.snap, src/components/Logos/HomeLogo/index.js, src/components/PaginationComponent/PaginationComponent.js, src/components/PaginationComponent/__tests__/__snapshots__/PaginationComponent.test.js.snap, src/components/TabLists/TabLists.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/layouts/EmbedLayout.js, src/utils/path.js, src/views/EmbedderView/EmbedderView.js, src/views/EmbedderView/components/IFramePreview.js, src/views/EmbedderView/embedderConfig.js, src/views/EmbedderView/utils/utils.js, src/views/MapView/MapView.js, src/views/MapView/components/MarkerCluster/clusterUtils.js, src/views/MapView/index.js, src/views/MapView/utils/mapActions.js, src/views/MapView/utils/useMapUnits.js
- Added option to embedded view parameter to include list of units next to the embedded map. This improves embedded view accessibility.
-  Created a new hook that defines what data should be shown on map. Previously this was done as a complicated function inside MapView component. Now the units shown on map can be accessed by other components, such as this new embedded unit list.
=> Embedded view unit list

src/components/TopBar/SMLogo/SMLogoComponent.js, src/components/TopBar/SMLogo/__tests__/SMLogo.test.js, src/components/TopBar/SMLogo/__tests__/__snapshots__/SMLogo.test.js.snap, src/components/TopBar/SMLogo/index.js, src/components/TopBar/TopBar.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js
Added logo text to aria label so it matches visual text but also indicates what element click does.
Test with screenreader
=> Add logo text to aria label

browserTests/areaTest.js, src/views/AreaView/AreaView.js
Bug: Opening embedder tool in area view and then closing the tool caused a crash when returning to area view.
=> Fix area view embedder tool bug

jestSetup.js, src/components/TopBar/LanguageMenu/LanguageMenuComponent.js, src/components/TopBar/LanguageMenu/__tests__/LanguageMenu.test.js, src/components/TopBar/LanguageMenu/index.js, src/components/TopBar/SMLogo/SMLogoComponent.js, src/components/TopBar/SMLogo/__tests__/SMLogo.test.js, src/components/TopBar/SMLogo/__tests__/__snapshots__/SMLogo.test.js.snap, src/components/TopBar/SettingsButton/SettingsButton.js, src/components/TopBar/SettingsButton/__tests__/__snapshots__/SettingsButton.test.js.snap, src/components/TopBar/TopBar.js, src/utils/path.js
Add aria-current attributes to several elements. (Accessibility report page 20)
=> Accessibility: current page aria-current

src/components/SearchBar/SearchBarComponent.js
See trello card: https://trello.com/c/cBDfcSE6/1175-bugi-mobiilissa-etusivun-haun-fokus-on-ruudun-yläpuolella
=> Fix ios keyboard bug

src/views/MapView/components/TransitStops/TransitStops.js
Fix error caused by duplicate keys
=> Fix errors caused by duplicate keys

browserTests/views/addressTest.js, src/views/AddressView/AddressView.js
Tests for checking list items clicks, close by services tab and links
=> Add new browser tests for address view

browserTests/views/serviceTreeTest.js, src/views/ServiceTreeView/ServiceTreeView.js
Tests to check:
- collapse element
- removing selections
- search works
=> Add service tree browser tests

src/components/AddressSearchBar/AddressSearchBar.js, src/utils/orderUnits.js, src/views/SearchView/SearchView.js
- Fixed missing address results on English language
- Improved address results list stability. Multiple fetches caused inconsistency on the results.
- Added map focus to address search bar address selection. Needed to remove extra rerenderings on sorting parameter change
=> Address search bar fixes

browserTests/views/embeddedViewsTest.js, browserTests/views/homeTest.js, package-lock.json, package.json, src/components/ToolMenu/MeasuringStopButton/__tests__/__snapshots__/MeasuringStopButton.test.js.snap, src/views/HomeView/HomeView.js, webpack.config.js
- Update libraries
- Remove old Servicemap link from front page
=> Release 1.5.5

src/components/SMSwitch/index.js, src/components/index.js, src/views/AreaView/AreaView.js, src/views/AreaView/components/DistrictAreaList/DistrictAreaList.js, src/views/AreaView/components/DistrictToggleButton/DistrictToggleButton.js, src/views/AreaView/components/DistrictUnitList/DistrictUnitList.js, src/views/AreaView/components/GeographicalDistrictList/GeographicalDistrictList.js, src/views/AreaView/components/GeographicalTab/GeographicalTab.js, src/views/AreaView/components/ParkingAreaList/ParkingAreaList.js, src/views/AreaView/components/ServiceTab/ServiceTab.js, src/views/AreaView/components/StatisticalDistrictList/StatisticalDistrictListComponent.js, src/views/AreaView/components/StatisticalDistrictList/StatisticalDistrictListContent.js, src/views/AreaView/styles.js
Area view list style updates.
I tried first creating a new AccordionListItem component but it broke so many thing that I just decided to start over and only change styles. We have to many different functionality in each view that unified component would require intensive work and testing to make sure everything works well.
=> Update area view list item styles

.env.example
Fix trailing slash in example `.env` file.
First commit and pr! yay!
=> Add trailing slash

src/views/MapView/MapView.js
=> Fix unitView when unit does not have location or geometry prop

src/components/AddressSearchBar/AddressSearchBar.js
=> Use user language as param for address search

src/redux/reducers/district.js
=> Fix loading indicator on district load

src/views/UnitView/UnitView.js
https://trello.com/c/Is0njq8y
Kuva lisätty perustiedot-välilehden viimeiseksi kun käyttäjä on mobiililaitteella
=> Add picture to mobile unit view

src/components/BackButton/BackButton.js, src/components/BackButton/styles.js, src/components/TitleBar/TitleBar.js, src/components/TitleBar/styles.js, src/components/index.js, src/views/UnitView/UnitView.js, src/views/UnitView/styles/styles.js
Lisätty uusi variantti BackButtonille jossa on enemmän paddingToppia
=> Fix unit view top bar

src/components/SettingsComponent/SettingsComponent.js, src/components/SettingsComponent/index.js, src/components/SettingsComponent/styles.js, src/components/index.js, src/redux/actions/settings.js, src/redux/reducers/settings.js, src/redux/rootReducer.js, src/utils/settings.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/AccessibilityInfo/AccessibilityInfo.js
https://trello.com/c/qAcXkxeb
TODO
=> Use new settings component

src/redux/actions/search.js
=> Include connections when searching for units in embedded mode

src/utils/dataVisualization.js
=> Release v1.6.6

src/components/SettingsComponent/SettingsComponent.js
https://trello.com/c/EfMzvcAN
Logic was copied from src/components/Settings/Settings.js:258
=> Change map type when user selects visually impaired sense setting

src/components/SettingsComponent/SettingsComponent.js, src/utils/settings.js
https://trello.com/c/jpajvjDs
and
https://trello.com/c/m3pVVAUm
also this was reported recently
https://trello.com/c/aAjvX5tm
=> Fix mobility setting visibility

src/views/AreaView/components/DistrictAreaList/DistrictAreaList.js
=> Fix municipality of address

src/utils/newFetch/ServiceMapAPI.js, src/views/AreaView/components/ParkingAreaList/ParkingAreaList.js, src/views/AreaView/components/ServiceTab/ServiceTab.js
=> Add vantaa parking

src/views/AreaView/components/ParkingAreaList/ParkingAreaList.js, src/views/AreaView/components/ServiceTab/ServiceTab.js
Ei näkynyt mitään alueita kun ei yhtään kaupunkia ollut valittuna
https://trello.com/c/49uuqxgh
=> Fix visibility of parking areas when no cities are selected

src/views/MapView/components/TransitStops/TransitStops.js
=> hide bikestations with other transit stops

src/redux/actions/search.js
https://trello.com/c/6dJFhIOC
Huomaa että tämä ei korjaannu näillä muutoksilla https://trello.com/c/Og6eJclM
=> Fix visibility of unit contact info

.github/workflows/ci.yml, src/views/MapView/components/Districts/ParkingAreas.js
=> Add colors for vantaa parking areas

src/i18n/fi.js
=> Fix translation

src/components/ResultOrderer/ResultOrderer.js, src/utils/mapUtility.js, src/views/AreaView/AreaView.js, src/views/MapView/MapView.js
=> Fix map pane bug

src/views/InfoView/InfoView.js
=> New app info texts in finnish

src/views/UnitView/UnitView.js
=> Fix map getCenter bug

src/components/Navigator/Navigator.js
=> Fix embed state when redirecting

.gitignore, server/sitemapMiddlewares.js
Huom: muutos menossa suoraan master-haaraan
=> Add new location for sitemap

browserTests/views/unitPageTest.js, src/components/MenuButton/DropDownMenuButton/DropDownMenuButton.js, src/components/MenuButton/MenuButton/MenuButton.js, src/components/MenuButton/MenuButton/styles.js, src/components/MenuButton/OwnSettingsMenuButton/OwnSettingsMenuButton.js
Revertoidaan huonosti toimiva "fix"
=> Revert "Fix map setting scroll"

package-lock.json, package.json
See failing pr https://github.com/City-of-Helsinki/servicemap-ui/pull/1010
Notice diff between these two commits in `package-lock.json`
=> Upgrade testcafe 3.0.1->3.1.0

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/UnitView/components/ContactInfo/ContactInfo.js
=> Fix link text for other address

browserTests/generic/generalTest.js, src/components/SettingsDropdowns/SettingsDropdowns.js, src/redux/actions/search.js, src/utils/filters.js, src/utils/newFetch/ServiceMapAPI.js
Korjaukset toteutettu tämän [kortin](https://trello.com/c/FbfvK6Dv/1312-5-hyvinvointialueet-asetusvalikkoon) uusimpien kommenttien pohjalta.
=> Wellbeing area settings improvements

src/redux/reducers/settings.js
I was getting
```
Warning: Failed prop type: Invalid prop `mobility` of type `boolean` supplied to `Navigator`, expected `string`.
at Navigator (webpack://servicemap-ui/./src/components/Navigator/Navigator.js?:53:81)
....
```
=> Null initial value for some reducers

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/utils/newFetch/ServiceMapAPI.js, src/views/ServiceTreeView/ServiceTreeView.js
- Update service node fetch to include root_department parameter that is used in organization filtering
- Update service tree view node unit counts to count organizations
=> Organization settings in service tree views

azure-pipelines-devtest.yml, src/components/MenuButton/MenuButton/MenuButton.js
Fix
- Map tool menu scroll when zoomed or screen is small
=> Release v2.0.12

src/utils/newFetch/HTTPClient.js
=> Force trailing slash for unit-calls

src/utils/newFetch/HTTPClient.js, src/utils/newFetch/ServiceMapAPI.js, src/views/ServiceTreeView/ServiceTreeView.js
Lasketaan palvelupuun solmujen tulosten lukumäärä nopealla getCount kutsulla. Parannettiin myös getCount kutsu palauttamaan vain id haun nopeuttamiseksi.
=> Dynamic service tree result count

sonar-project.properties
Exclude tests from SonarCloud analysis recursively.
=> Exclude tests from SonarCloud analysis recursively

src/components/SMCookies/SMCookies.js
[Refs](https://trello.com/c/81vIOlQO/1536-siirry-p%C3%A4%C3%A4sis%C3%A4lt%C3%B6%C3%B6n-nappi-tulee-esille-ev%C3%A4steiden-hyv%C3%A4ksymisen-j%C3%A4lkeen)
=> Do not display view-title after cookies

package-lock.json, package.json
Add missing http-status-typed dependency to resolve module not found error during build process.
=> Fix module not found error

src/index.css, src/views/MapView/components/ElevationControl/ElevationControl.js
Height profile updates:
- Use orange highlight colour for 3D-lines
- Increase close-button size
=> Height profile updates

.env.example, .github/workflows/ci.yml, server/dataFetcher.js, src/components/ListItems/ReservationItem/ReservationItem.js, src/redux/actions/selectedUnitReservations.js, src/utils/fetch/constants.js, src/views/UnitView/components/ExtendedData/ExtendedData.js, src/views/UnitView/components/UnitDataList/UnitDataList.js
Fetch reservations from the new reservations API.
[Refs](https://trello.com/c/HRaFNeIo/1480-uuden-tilanvaraus-rajapinnan-k%C3%A4ytt%C3%B6%C3%B6notto)
=> Replace old reservations API with new one

browserTests/utility/index.js, package-lock.json, package.json, src/App.js, src/views/UnitView/UnitView.js
Add HDS back now that the React v18 upgrade issues are fixed.
=> Revert "Temporary remove HDS and comment out code that uses it"

src/components/CardSmall/CardSmall.js, src/components/MenuButton/MenuButton/MenuButton.js, src/views/AreaView/components/SideBar/SideBar.js
Fixing UI heading levels to be more logical.
=> fix: a11y heading level fixes PL-20

browserTests/generic/mapTest.js, src/assets/icons/icon-arrow-next.svg, src/assets/icons/icon-arrow-previous.svg, src/index.css, src/views/MapView/MapView.js, src/views/MapView/components/ElevationControl/ElevationControl.js, src/views/SearchView/SearchView.js
https://github.com/City-of-Helsinki/servicemap-ui/releases/tag/untagged-e864986518be283b5733
=> Release v2.0.32

.github/workflows/analyze-code.yml, .github/workflows/ci.yml, pipelines/palvelukartta-ui-dev.yml, pipelines/palvelukartta-ui-review.yml
Pipelines and workflows using main branch
[PL-65](https://helsinkisolutionoffice.atlassian.net/browse/PL-65)
[PL-65]: https://helsinkisolutionoffice.atlassian.net/browse/PL-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: main branch PL-65

.env.example, .github/workflows/ci.yml
Refs [PL-78](https://helsinkisolutionoffice.atlassian.net/browse/PL-78)
[PL-78]: https://helsinkisolutionoffice.atlassian.net/browse/PL-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update Reservations API URL:s

src/views/MapView/components/TransitStops/util/util.js
=> chore: use RAIL as train type

.github/workflows/ci.yml, Dockerfile, README.md, config/default.js, package.json, sonar-project.properties, webpack.config.js, yarn.lock
Common CI workflow
https://helsinkisolutionoffice.atlassian.net/browse/PL-87
Lint is now just an empty command to get common ci running. There is a separate task for linter settings.
=> ci: common ci flow PL-87
