City-of-Helsinki/servicemap-ui

config/paths.js, src/components/ListItems/UnitItem/UnitItem.js, src/components/MobileBottomNavigation/MobileBottomNavigation.js, src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/layouts/DefaultLayout.js, src/views/EventDetailView/EventDetailView.js, src/views/Map/MapContainer.js, src/views/Map/components/MapView.js, src/views/Map/utils/mapActions.js, src/views/MobileMapView/MobileMapView.js, src/views/SearchView/SearchView.js, src/views/UnitView/UnitView.js
* Add show on map button to mobile unit view
* Add top bar to map (is either search bar or title bar depending on page)
* Modify mobile bottom navigation so that the correct page is highlighted when coming back to homepage using back-button.
* Add new variable fullMobileMap to defaultLayout styling. If fullMobileMap is true, use styling for map view without bottom navigation and search-bar
=> Add show on map button to mobile unit view

src/redux/actions/services.js, src/views/SearchView/SearchView.js, src/views/ServiceView/ServiceView.js
Zoom to berries only when new search or service data is fetched.
=> Fix/zoom only when search- or service-data changes

src/components/Settings/Settings.js, src/components/Settings/SettingsTitle.js
Swapped Close-button and close icon placements in Settings view to help differentiate which closes the actual settings view.
=> Swap snackbar close button stylings with settings close button

src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/layouts/DefaultLayout.js, src/layouts/EmbedLayout.js
Adding aria-label to map wrapper to inform user that map exists. This way map settings in settings page are not as confusing for screen reader users.
=> Add aria label text for map element

src/utils/fetch/constants.js
Try to promote single-occurrence events over long periodical ones.
=> Tweak unit event sort order

src/components/SearchBar/SearchBar.js, src/utils/index.js
Fix the issue caused by search queries with multiple words. Previously it would search again when changing to next result list page.
Also prioritise previousSearch over initialValue in search bar
=> Replace extra "+" symbols from serch queries

src/components/SearchBar/SearchBar.js
Previously, if previous search is service nodes search (search initiated from service tree), search bar would get odd previous search test.
=> Remove previous search if search is service nodes

server/server.js
This setting is required for production deployments.
=> Trust proxies so HTTP host parameters from proxies are respected

src/components/ListItems/UnitItem/UnitItem.js
Fixed problem where distance=0 was rendered as `0` and not `0m` For example /fi/address/helsinki/Arkadiankatu/25 gives data where distance to some units is zero.
=> Prevent distance from being rendered as 0

.babelrc, webpack.config.js
Fix for internet explorer issue where polyfills were not loaded correctly.
Should fix issues for pages like 
- `/sv/address/esbo/gårdsbrinken/1`
- `/sv/embed/address/esbo/gårdsbrinken/1` 
- `/sv/address/esbo/karvasbackavägen/6`
=> Fix issue where polyfill builtins weren't loaded properly

src/views/AddressView/AddressView.js, src/views/AddressView/utils/fetchDistricts.js, src/views/DivisionView/DivisionView.js, src/views/DivisionView/fetchDivisionDistrict.js, src/views/MapView/MapView.js, src/views/MapView/components/Districts.js, src/views/MapView/utils/mapActions.js, src/views/UnitView/UnitView.js
* Fixed issue where districts with multiple area bounds would only draw first area
* Removed district coordinate swapping from fetch functions and instead do swapping when drawing/focusing to map
* Changed highlighted district type from array to object (since there can only be one highlighted district) 
* Add missing units from districts. (For example Kalasatama health station district now shows Kalasatama health station)
* Move area unit popup closer to unit icon
=> District area drawing fix

src/components/BackButton/BackButton.js, src/components/TitleBar/TitleBar.js, src/components/TitleBar/styles.js
- Previously back buttons in title bars had incorrect blue keyboard focus (For example in expanded search window)
=> Add correct focus to title bar back button

src/views/ServiceTreeView/ServiceTreeView.js, src/views/ServiceTreeView/styles.js
- Service tree blue area buttons used default focus (blue) instead of correct one (white)
=> Add correct focus contrast to top area buttons

src/components/Settings/Settings.js, src/components/TitleBar/styles.js
Previously clicking save or cancel on settings page notification box would make screen readers stuck. (Focus is nowhere). Now it focuses back to settings title.
=> Fix focus loss on settings confirmation click

package-lock.json, package.json, webpack.config.js
Fixes a memory leak in the Sentry client.
Eases debugging with stack traces.
Still bundles material ui, because otherwise the page styles break.
=> Do not bundle node_modules dependencies in the server webpack bundle

src/views/MapView/utils/unitMarkers.js
Unit page embeds showed single unit marker which didn't get click event when embeded.
=> Add marker event always if embed is active

src/views/UnitView/components/ContactInfo.js
Fix problem with unit page breaking app if no location data exists. Now route data is hidden if location can't be retrieved from unit data
=> Hide route data if location doesn't exist

src/components/DrawerMenu/DrawerMenu.js, src/components/PaperButton/PaperButton.js, src/components/PaperButton/index.js, src/components/SearchBar/SearchBar.js, src/components/ServiceMapButton/ServiceMapButton.js, src/components/ServiceMapButton/index.js, src/components/Settings/Settings.js, src/components/SettingsInfo/SettingsInfo.js, src/components/TopBar/TopBar.js, src/components/TopBar/index.js, src/i18n/translations/en.js, src/i18n/translations/fi.js, src/i18n/translations/sv.js, src/index.css, src/views/HomeView/HomeView.js, src/views/UnitView/UnitView.js
- Added correct aria-labeling to drawer menu button
- Modifed button components so that the text inside the button is aria-hidden, and the button itself has the text as aria-label (iOS mobile VoiceOver would only read the text inside the button ignoring the button and its state completely)
- Fixed issue with  focus disappearing from page on entering settings page
- Added aria-hidden to "show on map" -button on unit page
- Added "search" -type to search field, so that virtual keyboard has correct layout
=> Mobile accessibility

src/utils/localStorage.js
Prevents crash when user has blocked cookies on browser.
=> LocalStorageUtility add try-catch to when setting localStorage

src/components/PaperButton/styles.js
Fix issue with home view paper buttons not staying in line with searchbar.
=> Change PaperButton to adjust to container width

src/redux/selectors/results.js, src/views/MapView/index.js
Prevent map clustering changes when unit ordering is changed by user. Previously map markers were re-rendered every time user changed the order priority for unit listing. This caused list data to change and affected the map clustering by changing cluster positions.
This solution introduces new getProcessedMapData selector which completely ignores ordering the data.
=> Prevent map clustering from changing when list ordering is changed

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/InfoView/InfoView.js
Update title on front page and move link location to top of info view. Possibly temporary solution.
=> Make acessibility statement more visible

package-lock.json, package.json, src/components/DropDownMenuButton/DropDownMenuButton.js, src/components/DropDownMenuButton/styles.js, src/components/ListItems/UnitItem/index.js, src/components/ToolMenu/ToolMenu.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/redux/selectors/ordering.js, src/redux/selectors/results.js, src/redux/selectors/service.js, src/redux/selectors/unit.js, src/utils/downloadData.js, src/utils/orderUnits.js, src/views/AddressView/index.js, src/views/AddressView/utils/fetchAddressUnits.js, src/views/EventDetailView/EventDetailView.js, src/views/MapView/MapView.js, src/views/MapView/index.js, src/views/MapView/utils/mapActions.js, src/views/SearchView/SearchView.js, src/views/SearchView/index.js, src/views/ServiceView/ServiceView.js, src/views/UnitView/index.js
- Refactor reselect selectors to work correctly by removing state passing: previously state was given as parameter to selector, this causes memoization to not work.
- Update react-redux to get new redux hook useSelector, that is used in download tool hook.
- Add download tool hook
- Changed tool menu styles
**Note**: new redux hooks allows easier access to state on functional components. These can be used to replace the connect HOC and mapStateToProps.
=> Download tool + memoized selector refactor

src/views/UnitView/components/Services/Services.js
If unit does not have any services the API returns `root_service_nodes` as null. This broke the “Services and events” tab in the unit details.
=> Check if unit has root service nodes

src/views/AreaView/AreaView.js, src/views/AreaView/components/AreaTab/AreaTab.js
- Use reduce() to group district data instead of map()+ filter()
- Sort district data by period year
- Do fetch result handling after all concurrent district fetches have finished (so that the order of districts on UI is not determined by fetch speed)
=> Improve district grouping and sorting

config/default.js, server/server.js, src/redux/actions/selectedUnitAccessibility.js, src/utils/fetch/constants.js, src/views/UnitView/UnitView.js
Helsinki’s accessibility sentences are loaded from a system with servicemap’s unit ids. Add support for loading the sentences from a system that uses PTV ids as identifiers.
Settings for using this API:
```
ACCESSIBILITY_SENTENCE_API: <URL>
USE_PTV_ACCESSIBILITY_API="true"
```
=> Add support for loading accessibility sentences with PTV id

src/views/FeedbackView/FeedbackView.js
Feedback dialog showed error message when `modalOpen` changed from `send` to `false`. It seems like the dialog content updates before `open` value is changed to `false`. This caused flashing error message because text is changed in dialog but it did not close the dialog right away.
Changed dialog to not be rendered if `modalOpen` is `false`
=> Prevent dialog showing error message when modalOpen changes to false

src/views/MapView/components/Districts/Districts.js
https://github.com/Leaflet/Leaflet/issues/7255
Leaflet double click bug on safari causes geographical district map clicks to fail.
=> Fix safari + leaflet map click issue

src/components/TabLists/TabLists.js
There was a problem with `t` parameter trying to get index out of bound from given data array. This could happen when person searches results with multiple tabs, selects last tab, and changes city settings so that results don't give multiple tabs.
=> Fix TabLists out of bound index by defaulting to 0

src/views/MapView/components/MarkerCluster/MarkerCluster.js
Disabled cluster interaction during measuring mode also on clusters that are generated/modified by zooming map.
=> Fix measuring mode interaction on marker clusters

src/views/MapView/MapView.js
Use reducer to parse duplicate map units in address view.
=> Parse duplicates away from adminDistrict mapUnits

src/components/ReadSpeakerButton/ReadSpeakerButton.js
Hiding ReadSpeaker button from screen readers until ReadSpeaker fixes their accessibility
=> Hide ReadSpeaker button from screenreaders

src/components/ListItems/ResultItem/ResultItem.js, src/components/ListItems/ResultItem/__tests__/ResultItem.test.js
Distance object was by default an empty object making distance.srText to `undefined` rather than empty text
=> Use distance srText or default properly to empty

src/i18n/fi.js, src/views/AreaView/AreaView.js
Added title bar to area view. Decided to use "p" instead of heading, since the page title with the same name is just before title bar.
=> Add back button to area view

src/components/TitleBar/TitleBar.js, src/views/AreaView/components/UnitTab/UnitTab.js
- Units without location caused a crash when area unit tab was opened with address selected (example: choose an address, choose Finnish primary school area, select unit tab)
- Updated title bar to allow p tag as title prop. New area view title bar caused errors.
=> Area view bugs

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/AreaView/components/UnitTab/UnitTab.js
UnitTab didn't show anything if district didn't have any units. Added info text to solve this problem.
=> Add info text for UnitTab when district data doesn't have any units

src/components/NewsInfo/NewsInfo.js
Fixed news info external url handling. External url was expecting string even though API returned translated object.
=> Fix external url to use getLocaleText function for translations

src/components/SearchBar/SearchBar.js, src/i18n/fi.js
Added skip links to before and after suggestion list.
This gives mobile screen reader user ability to close suggestions which was impossible before. This solution isn't perfect because user still can just move past these links leaving suggestions box over the current view.
=> Add skip links for suggestions box

server/ieMiddleware.js, server/server.js
New express middlware for handling IE warning page. Prevents user from accessing normal page on IE because there is syntax errors that polyfills fail to count for.
=> Add express middleware for handling IE warning

src/components/DescriptionText/DescriptionText.js
Description text includes HTML code on event view. Some descriptions contain <br> elements without aria-hidden attribute. Change `<br>` elements to `<br aria-hidden="true" />`
Example: https://palvelukartta.hel.fi/fi/event/helmet:215044
=> Hide description <br> elements from screen readers

src/views/MapView/components/UserMarker/UserMarker.js, src/views/PrintView/PrintView.js
If user location is available, location icon crashes print view.
=> Exclude user marker from print markers

src/views/PrintView/PrintView.js
Only add markers that are unit markers or clusters. 
Print view was crashing because it was fetching any leaflet marker including transit stops. Changed marker fetching to only get markers that have icons with class `unitMarker` or `unitClusterMarker`. Also added check that confirms description has existing first unit.
=> Check that description has units

src/components/TopBar/TopBar.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js
Accessibility report 4.1. Add more descriptive aria-label for contrast button because for users who can't see the change button seem to do nothing
=> Add dynamic aria-label for contrast change button

src/views/MapView/styles.js
Accessibility report 3.7: Focus indicator moves to "invisible" element. Focus moved to map without focus indicator. Added focus indicator for map to show user where they currently are.
=> Add focus indicator to map

src/views/EventDetailView/EventDetailView.js
Previously event view would not center map to unit location if arriving straight to event view. Example event url: palvelukartta.hel.fi/fi/event/helmet:220550
=> Add map centering to event view

src/components/Dialog/DownloadDialog/utils.js, src/utils/newFetch/HTTPClient.js, src/utils/newFetch/ServiceMapAPI.js
New HttpClient and ServiceMapAPI classes for better API fetching.
HttpClient has in-built abort handling and next fetching logic.
ServiceMapAPI extends HttpClient and contains all required fetch data in individual methods that better describe what is being fetched from Servicemap API.
This way we can get rid of the constants file and messy fetch logic used in previous solution.
=> New HTTPClient and ServiceMapAPI classes for imporved fetch handling

src/layouts/components/ViewRouter/ViewTitle/ViewTitle.js
Check if cookiehub banner is hidden before focusing to site title
=> Prevent automatic focus to site title if cookiehub banner is not hidden

src/views/AreaView/AreaView.js
Area view: choosing an address and an area then opening embedder tool and closing it caused a crash.
=> Fix area view embedder crash

src/components/SearchBar/SearchBar.js, src/components/SearchBar/components/SuggestionBox/SuggestionBox.js, src/components/SearchBar/components/SuggestionBox/styles.js, src/components/SearchBar/styles.js
There was an issue with suggestion box overflowing out of sidebar wrapper when wrapper has `overflow hidden`. This was caused by suggestion box setting overflow hidden. For solution I changed overflow hidden only to appear in mobile widths.
Suggestion box also had horizontal overflow scroll being shown. This is caused by list item dividers having margins that take it out of parent bounds. I've added `overflow-x: hidden` for suggestion container.
Removed `max-height` from suggestion area because it doesn't seem to do anything because it is not responsive to different heights.
Changed searchbar wrapper to relative position so suggestion area can be set width 100% based on wrapper. This saves us from having to worry about having correct `left` and `right` attributes for suggestion area …
=> Prevent vertical overflow being hidden when not in mobile

browserTests/mapTest.js
Update mapTest geometry check to use existing data
=> Fix map test geometry check using data that doesn't exist anymore

server/server.js, server/sitemapMiddlewares.js, server/utils.js
Rather than only disabling sitemap when SERVER_TYPE is staging change sitemap to be disabled by default. Changed to sitemap creation to check if SERVER_TYPE is production and NODE_ENV is production. This makes sure sitemap is not created in development mode or in staging server.
This requires changing environment variables in production server. Need to add SERVER_TYPE=production into envrionment variables
=> Create sitemap only when SERVER_TYPE is production

src/views/AreaView/AreaView.js, src/views/AreaView/components/GeographicalDistrictList/GeographicalDistrictList.js
Selecting an area type in area view now zooms out or in to fit the areas to the map. Selecting the first geographical subdistrict (single neighborhood for example) will also zoom the map instead of just panning.
=> Focus map to selected area

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/AreaView/AreaView.js, src/views/AreaView/components/DistrictAreaList/DistrictAreaList.js, src/views/AreaView/components/ServiceTab/ServiceTab.js
Units will be removed from rescue areas. Replace service unit list with area list (same as rescue districts and rescue sub districts).
Fix area focus error
=> Use district area list on rescue area service list

src/components/Navigator/Navigator.js, src/utils/tracking.js
Previously Matomo was not working even if user allowed cookies. Moved cookie consent check to tracking function
=> Move cookie consent check to tracking function

src/components/SearchBar/SearchBarComponent.js, src/views/SearchView/SearchView.js
Adding parameter "units" with list of id:s to search page url will show only the selected units.
Example url: https://palvelukartta.hel.fi/fi/embed/search?units=8215,51342
=> Add option for multiple unit embedding

server/dataFetcher.js, src/views/MapView/MapView.js, src/views/UnitView/UnitView.js
Some embedded units with areas needed to also show nearby units of certain service. Now extra services with distance filter can be added with url parameters: /embed/unit/68398?services=819&distance=500
=> Add option for adding services to unit view map

src/redux/actions/services.js, src/utils/newFetch/ServiceMapAPI.js
Problem: this multiple service fetch is taking too long. https://palvelukartta.hel.fi/fi/embed/unit/68398?services=155,239,254,311,312,344,345,389,917,399,400,401,410,415,916,961,912,577,672,767,786,791,813,819&distance=50
Fixed it by concurrently searching the service unit result pages, instead of searching the pages one after another.
=> Add concurrent search to embedded multiple services fetch

config/paths.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/layouts/components/ViewRouter/ViewRouter.js, src/views/UnitView/components/ExtendedData/ExtendedData.js, src/views/UnitView/components/UnitDataList/UnitDataList.js, src/views/UnitView/components/UnitsServicesList/UnitsServicesList.js
Bug: school service list showed duplicate services. Example: https://palvelukartta.hel.fi/fi/unit/6926/educationServices
The extended list showed the services for both periods in the same list. 
Fixed this by adding period to url to define which period services should be shown (example url: unit/6926/educationServices/2022–2023)
=> Fix duplicate period services

src/index.css, src/layouts/EmbedLayout.js, src/views/MapView/components/MarkerCluster/MarkerCluster.js, src/views/MapView/components/PanControl/styles.js, src/views/MapView/components/TransitStops/TransitStops.js
On smaller embedded views (mobile) marker popups were hard to use. Servicemap logo would be on top of the popup and usually popup were opened outside of screen bounds.
Moved logo to bottom and added autoPan to marker popups
Also improved mobile click responsiveness
=> Mobile embedded view fixes

src/components/ResultOrderer/ResultOrderer.js
Result orderer select element was missing linked label. Now it should read the label when navigating to the element. (Accessibility report page 32)
=> Add better label for result order select element

src/components/AddressSearchBar/AddressSearchBar.js, src/components/DropDownMenuButton/DropDownMenuButton.js, src/components/Link/Link.js, src/components/Lists/ResultList/ResultList.js, src/components/PaginationComponent/PageElement.js, src/components/Settings/Settings.js, src/components/TabLists/TabLists.js, src/components/TitleBar/TitleBar.js, src/layouts/DefaultLayout.js, src/layouts/EmbedLayout.js, src/layouts/components/ViewRouter/ViewTitle/ViewTitle.js, src/views/FeedbackView/FeedbackView.js, src/views/MapView/components/PanControl/PanControl.js, src/views/PrintView/PrintView.js, src/views/SearchView/SearchView.js
After MaterialUI update some components have thrown error when tabIndex has been string. Changed all react components use number for tabindex props.
=> Fix tabindex values to numbers for elements that utilize buttonbase

browserTests/views/unitPageTest.js
There seems to be a bug with new window being closed when trying to get use ClientFunction. Maybe it's caused by multiple ClientFunctions being called in single test.
Separating hearing map test to own test seems to solve this.
=> Fix closing window issue by separating hearing map test to own test

jestUtils.js, src/components/FocusableSRLinks/__tests__/FocusableSRLinks.test.js, src/components/ListItems/ResultItem/__tests__/ResultItem.test.js, src/components/ListItems/SimpleListItem/__tests__/SimpleListItem.test.js, src/components/ListItems/SuggestionItem/__tests__/SuggestionItem.test.js, src/components/Lists/ResultList/__tests__/ResultList.test.js, src/components/Lists/ResultList/__tests__/__snapshots__/ResultList.test.js.snap, src/components/PaginationComponent/__tests__/PageElement.test.js, src/components/PaginationComponent/__tests__/PaginationComponent.test.js, src/components/PaginationComponent/__tests__/__snapshots__/PaginationComponent.test.js.snap, src/components/PaperButton/__tests__/PaperButton.test.js, src/components/PaperButton/__tests__/__snapshots__/PaperButton.test.js.snap, src/components/SMRadio/__tests__/SMRadio.test.js, src/components/SearchBar/components/__tests__/CloseSuggestionButton.test.js, src/components/ServiceMapButton/__tests__/ServiceMapButton.test.js, src/components/ToolMenu/MeasuringStopButton/__tests__/MeasuringStopButton.test.js, src/components/ToolMenu/MeasuringStopButton/__tests__/__snapshots__/MeasuringStopButton.test.js.snap, src/components/TopBar/DrawerMenu/__tests__/DrawerButton.test.js, src/components/TopBar/LanguageMenu/__tests__/LanguageMenu.test.js, src/components/TopBar/MenuButton/__tests__/MenuButton.test.js, src/components/TopBar/MenuButton/__tests__/__snapshots__/MenuButton.test.js.snap, src/components/TopBar/SMLogo/__tests__/SMLogo.test.js, src/components/TopBar/SMLogo/__tests__/__snapshots__/SMLogo.test.js.snap, src/components/TopBar/SettingsButton/__tests__/SettingsButton.test.js, src/components/TopBar/SettingsButton/__tests__/__snapshots__/SettingsButton.test.js.snap
We had quite a bit duplicated code in jest tests. This PR moves Providers to single file and refactors jest test files to follow these changes. New solution uses same IntlProvider for each test which is using English locale. This means some tests had to be refactored to use English texts and updated snapshots.
=> Refactor jest providers to single file

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/ServiceTreeView/ServiceTreeView.js, src/views/ServiceTreeView/styles.js
There is an issue with user not having understanding of how service tree is supposed to work. So we've added an info text to describe in short how the service tree view is used. This should improve screen reader accessibility as well since user gets information about why search button is disable initially.
=> Add info text to describe service tree functionality for user

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/UnitView/components/ContactInfo/ContactInfo.js, src/views/UnitView/styles/styles.js
Add new kindergarten group contacts.  Data is part of connections with type "SUBGROUP" These were not shown previously but this PR introduces UI changes to show this data. Since subgroups are not necessarily kindergarten only data we've changed the text to be more generic in case someone adds subgroups for other services.
=> Add sub group contact informations to unit view

src/views/SearchView/SearchView.js
Hotfix: Fix looping service redirect
This was causing some embeds to infinitely loop since the url was giving 404 response and redirect handling wasn't handling this well. I've just commented the code until we can take a closer look at this.
=> Release v1.5.1

src/layouts/EmbedLayout.js, src/redux/actions/search.js, src/utils/newFetch/HTTPClient.js, src/utils/newFetch/LinkedEventsAPI.js, src/views/MapView/utils/useMapUnits.js, src/views/SearchView/SearchView.js
Fixed some embed urls that did not work with the new search
- Unit id list: https://palvelukartta.hel.fi/fi/embed/search?units=8215,51342,8264,32359
- Events: https://palvelukartta.hel.fi/fi/embed/search?events=yso:p4354
- Address: https://palvelukartta.hel.fi/fi/embed/address/helsinki/El%C3%A4intarhantie%203/
=> New search embedded fixes (unit id list, events and addresses)

src/utils/dataVisualization.js, src/views/MapView/MapView.js
So our code failed on NPE because `this._mapPane` was `undefined` here https://github.com/Leaflet/Leaflet/blob/v1.7.1/src/map/Map.js#L1476 on atleast one instance of rerender after map type switch. Now the fix is to check for `mapPane` existence before resolving "center".
Could there be a more elegant solution by tweaking hooks? Probably yes.
Thoughts, questions and todo
- Why is this [src/redux/actions/map.js#](https://github.com/City-of-Helsinki/servicemap-ui/blob/develop/src/redux/actions/map.js#L4) `setMapRef` method used in `whenCreated` hook of leaflet map.
=> Check for mapPane existence before resolving center coordinates

.env.example
Sending statistics to backend failed because of double slash (https://api.hel.fi/servicemap//stats instead of https://api.hel.fi/servicemap/stats).
=> Fix api url to allow stats post

src/views/UnitView/components/ContactInfo/ContactInfo.js
liittyy tähän
'pvm/mpm' tieto tulee välillä
```
"call_charge_info": "pvm/mpm" 
```
ja välillä
```
"call_charge_info": {"fi": "pvm/mpm", ...} 
```
=> Fix call charge info when data is a string

server/sitemapMiddlewares.js
Update sitemap location relative to root as now dynamic sitemap writing is relative to the current working directory and writing there cannot be done due to default server write-restrictions.
Note that this change will be merged to master directly.
=> Update sitemap location relative to root

src/components/MenuButton/MenuButton/MenuButton.js
https://trello.com/c/HcSI1DXm/1424-yläpalkin-asetusvalikon-korkeuden-korjaus
Yläpalkin omat asetukset -valikon select-elementit jäivät piiloon edellisten valikkokorjausten jäljiltä.
Valikon komponentti muutettiin div elementistä  MUI:n Container komponentiksi, jotta sx tyylit voidaan asettaa.
=> Fix settings menu hidden overflow visibility

src/components/Dialog/Dialog.js, src/components/Navigator/Navigator.js, src/layouts/EmbedLayout.js, src/utils/newFetch/ServiceMapAPI.js, src/views/MapView/styles.js
Korjattiin seuraavat bugit:
- Tällä hetkellä unit-rajapinnan kutsujen only-parametrit rajaavat tuloksista perustiedot perushaun nopeuttamiseksi. Näitä tietoja tarvitaan tosin upotusnäkymissä. Lisättiin nämä puuttuvat tiedot upotuksissa hakuun. [Trellokortti](https://trello.com/c/jCSAXzwQ/1429-upotus-riippuen-hakulinkin-tekotavasta-tulee-eri-tiedot-näkyville)
- Uporustyökalusta poistuessa ja upotusnäkymän toimipistedialogin "näytä toimipisteen tiedot" painike ohjasivat virheellisesti upotusnäkymään normaalin näkymä sijasta [Trellokortti](https://trello.com/c/vHcZPzZk/1434-upotustyökalusta-poistuminen-ei-toimi-oikein)
- Pienillä näytöillä upotuksen toimipisteen tiedot -dialogi ei näy kunnolla. Näytetään dialogi fullScreen-tilassa näissä tapauksissa.
- Korjattiin toimipisteen popupin linkin …
=> Embedded view fixes

browserTests/views/addressTest.js, src/assets/icons/addressLocation.svg, src/components/SMIcon/index.js, src/views/MapView/components/AddressMarker/AddressMarker.js
Update the icon of the address location marker to similar as used in user location marker.
Old marker:
New marker:
=> Change address location marker icon

src/components/ToolMenu/ToolMenu.js, src/redux/actions/district.js, src/views/AreaView/AreaView.js
Parking spaces are mostly area data, but there are few category exceptions that are units added to the area view:
- parking garages
- shared car parking
- accessible street parking
The issue was that these units were not shown in the embedder tool when selected from the area list. This fix adds parameters to the embedder tool to show these units when their category is selected.
Screenshot of a working scenario:
[Refs](https://trello.com/c/d1B3dJqK/1560-vantaan-pys%C3%A4k%C3%B6intialueisiin-t%C3%A4pp%C3%A4-my%C3%B6s-upotukseen-mukaan)
=> Fix: show parking units in embedder tool

src/views/AreaView/AreaView.js
Selecting category of parking units from area list did not zoom and fit the map as in area data. Fix this by using `fitUnitsToMap` function when category with parking units is selected.
=> Fix: fit parking units to the map

src/views/UnitView/UnitView.js
No need to display unit source if unit type is private service.
[Refs](https://trello.com/c/UZfRKrit/1359-palvelukartalla-n%C3%A4ytett%C3%A4v%C3%A4t-tiedot-korjaus)
=> Do not display unit source if unit is private service

browserTests/views/settingsTest.js, src/views/HomeView/HomeView.js
As the setting can be found also in the navigation bar, remove them from the home view to give the news etc. more space.
Previously:
Now:
[Refs](https://trello.com/c/DauOldpG/1571-poistetaan-toinen-omat-asetukset-kohta)
=> Remove settings from the home view

src/views/AreaView/AreaView.js
When selecting a neighborhood, postcode or major district from the area list, the map should zoom to the selected area. Fix issue where the map did zoom but only momentarily and then zoomed back to the original view.
[Refs](https://trello.com/c/uEDYl6iL/1578-bugi-kun-valitsee-postinumeron-listasta-n%C3%A4kym%C3%A4-zoomaa-vain-hetkellisesti)
=> Fix zooming when selecting area from list

browserTests/views/unitPageTest.js, src/components/RouteBar/RouteBar.js, src/components/RouteBar/index.js, src/components/SettingsComponent/SettingsComponent.js, src/components/index.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/ContactInfo/ContactInfo.js, src/views/UnitView/utils/routeDetails.js
- Give more space to unit details by removing the settings from the unit view. The settings can be found in the navigation bar. 
- Add route info on top of the unit view (above the picture) to make it easier to find. 
[Refs](https://trello.com/c/MDzsMF6l/1579-poistetaan-omat-asetukset-toimipisteen-sivulta) & [Refs](https://trello.com/c/fpXSRI44/1569-siirret%C3%A4%C3%A4n-reittihaku-kuvan-ylle)
=> Unit view: add route info on top and remove settings

Dockerfile
Change the node image source to Amazon ECR to avoid hitting the Docker Hub pull rate limit.
[Refs](https://trello.com/c/EB2AQhjj/1586-vaihtoehtoja-dockerhubille)
=> Docker: Change node image source to ECR

src/components/Navigator/Navigator.js
Navigating from the embedder view to the info or feedback view did not work as expected. Instead of navigating to the correct view, the user was redirected the embed view.
[Refs](https://trello.com/c/3IP94sge/1442-1-upotusty%C3%B6kalusta-siirtyminen-ei-toimi-oikein)
=> Fix navigating from embedder view to info and feedback view

src/views/MapView/components/AddressPopup/AddressPopup.js
Add close button to address popup.
[Refs](https://trello.com/c/KrLgXDKO/1572-osoite-pop-up-sulje-rasti)
=> Add close button to address popup

src/components/TopBar/TopBar.js
Save the contrast theme to local storage to keep the theme when refreshing the page or opening the site again.
[Refs](https://trello.com/c/EKSqeLor/1452-2-kontrastiteema-tumma-teema-ei-lataudu-refreshill%C3%A4)
=> Save contrast theme to local storage

src/components/AddressSearchBar/AddressSearchBar.js
Previously used aria-label was not descriptive enough. Use label with the title instead.
[Refs](https://trello.com/c/C1qbbfYr/1281-1-osoitehakukent%C3%A4n-aria-labelin-selvitys)
=> Make AddressSearchBar more accessible

src/views/SearchView/SearchView.js
When searching for an address with a street number, if no results are found, search without the number.
[Refs](https://trello.com/c/X3UGIg3K/1488-osoitteet-listataan-osoitteet-kadunnimen-ja-kaupungin-perusteella-mik%C3%A4li-suoraa-osoitetta-ei-l%C3%B6ydy)
=> If no direct address is found, search without number

browserTests/views/searchTest.js, package.json
Currently, the testcafe tests in headless mode are failing/getting stuck in the CI pipeline. Replace chrome with firefox for now until more is known about the issue.
Comment out "Should set home address from url" test as it was too unstable in CI with firefox.
Also remove "--debug-mode" as it is not needed anymore.
=> browserTestCLI: replace chrome with firefox

src/views/SearchView/SearchView.js
Filter search results by bbox if embedded and bbox is provided.
[Refs](https://trello.com/c/05wXrbKK/1460-upotuksen-aluerajaus-ongelma-n%C3%A4ytt%C3%A4%C3%A4-zoomattaessa-kaikki)
Depends on [#256](https://github.com/City-of-Helsinki/smbackend/pull/256)
=> Embed view: filter search results by bbox

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/MapView/components/Districts/ParkingAreas.js
Add payment, duration and other details to the parking area popup forHelsinki parking areas.
Example of popup details before change: 
After:
Also, add some missing translations in popups.
[Refs](https://trello.com/c/6d6G6U6F/1556-pys%C3%A4k%C3%B6intialuiden-tietojen-n%C3%A4ytt%C3%A4minen-ilman-hiiren-n%C3%A4p%C3%A4ytyst%C3%A4?filter=*) & [Refs](https://trello.com/c/4wPSZvtc/1602-pys%C3%A4k%C3%B6intikieltojen-popuppien-tekstit-osin-rikki)
=> Helsinki parking areas: add more details to the popup 

src/views/MapView/components/UnitGeometry/UnitGeometry.js
The issue was that only the first area of a MultiPolygon was used in the UnitGeometry, meaning that only part of some areas were shown in the map. Updated the MultiPolygon case to iterate over all polygons.
Before the fix:
And after:
[Refs](https://trello.com/c/FpimYvAi/1553-luonnonsuojelualueiden-alue-geometrian-p%C3%A4ivitys-toimipisteisiin)
=> Fix: Handle all areas of MultiPolygon in UnitGeometry

.gitignore, config/default.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js
Remove unused municipality configs and translations. These raised warnings in the logs and were not used anywhere in the project anymore.
=> Remove unused configs and translations

src/components/SearchBar/SearchBarComponent.js
Make the SearchBar more accessible by using a label so the accessible name matches the visible name.
[Refs](https://trello.com/c/bSbK1Wen/1613-saavutettavuuskorjaukset-54-nimilappu-ja-saavutettava-nimi-eroavat)
=> Make SearchBar more accessible

browserTests/views/searchTest.js, src/utils/__tests__/settings.test.js, src/utils/settings.js
The accessibility shortcomings were not shown for visually impaired as the mapping had wrong naming for it.
=> Fix visually impaired in ACCESSIBILITY_MAPPING

src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/AreaView/components/GeographicalUnitList/GeographicalUnitList.js, src/views/AreaView/components/ServiceFilterContainer/ServiceFilterContainer.js, src/views/AreaView/components/ServiceFilterContainer/index.js, src/views/AreaView/components/StatisticalDistrictUnitList/StatisticalDistrictUnitListComponent.js, src/views/AreaView/components/styled/styled.js, src/views/AreaView/serviceFilterStyles.js
Add possibility to filter services in `GeographicalUnitList` view in same way as in the `StatisticalDistrictUnitList` view.
[Refs](https://trello.com/c/dD64Ssvm/982-2-rinnakkainen-haku-kaikkiin-n%C3%A4kymiin)
=> Add service filter to GeographicalUnitList view

.dockerignore, README.md, docker-compose.yml, package-lock.json, server/server.js
Updates:
- Update to support Sentry v.8
- Update Docker Compose configuration
- Update README
=> Add Sentry 8 and Docker / Docker Compose supports

server/dataFetcher.js, src/views/UnitView/UnitView.js
Make keyword check case-insensitive for 'kuuluvuuskartta' to handle different capitalizations.
[Refs](https://trello.com/c/hjhRGf4A/1627-laajasalon-terveysasema-kuulokartat-puuttuvat)
=> Make keyword check case-insensitive for 'kuuluvuuskartta'

src/App.js
Fixing cookie consent modal positioning on mobile, so that it doesn't overlap with bottom navigation.
=> fix: a11y cookie modal position on mobile PL-16

src/components/BottomNav/BottomNav.js, src/components/MapSettings/MapSettings.js, src/components/MobileSettingsHeader/MobileSettingsHeader.js
Add close button to "My settings" and "Map tools" settings widgets, so that they can be closed easily when navigating on keyboard.
=> fix: bottomNav settings add close button PL-18

src/components/SettingsDropdowns/SettingsDropdowns.js, src/components/TabLists/TabLists.js, src/i18n/en.js, src/i18n/fi.js, src/i18n/sv.js, src/views/ServiceTreeView/ServiceTreeView.js, src/views/UnitView/UnitView.js, src/views/UnitView/components/ContactInfo/ContactInfo.js
- settingsDropdown should announce clearing selections
- serviceTree, checkbox should announce "mixed" state, HDS Checkboxes do this internally
- Clicking on additional entrances link should focus on tab
=> Fixing  a11y status messages PL-17

src/views/SearchView/SearchView.js
Primary issue was:
fetchSearchResultsWithoutNumber previously relied on previousSearch
value to perform the second search. However, previousSearch can take
many forms depending on the search that was done, for example it might
just be a number when searching for a specific service_id. This would
cause the second search to happen possibly search?q={service_id} instead
of unit?service_id={service_id}.
Also fixed the regex removing only one number at a time. 
https://helsinkisolutionoffice.atlassian.net/browse/PL-32
=> Fix service producing wrong results

browserTests/generic/mapTest.js, src/assets/icons/icon-arrow-next.svg, src/assets/icons/icon-arrow-previous.svg, src/index.css, src/views/MapView/MapView.js, src/views/MapView/components/ElevationControl/ElevationControl.js
Allow unit MultiLineString scrolling when unit geometry has multiple line segments in it.
Browsing segments happen through new next- and previous-buttons in the height profile component's left bottom corner.
Also added TestCafe browser tests for the height profile.
Desktop-layout:
Mobile-layout:
Refs: [PL-41](https://helsinkisolutionoffice.atlassian.net/browse/PL-41)
[PL-41]: https://helsinkisolutionoffice.atlassian.net/browse/PL-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow unit MultiLineString scrolling

src/views/MapView/components/ElevationControl/ElevationControl.js
Latest height profile refactoring efforts induced a new regression bug:
`Uncaught ReferenceError: control is not defined` when mouse is hovered on top of a line route.
Fix this by moving route handlers back inside the useEffect-hook.
=> Move route handlers inside useEffect-hook

src/components/ErrorBoundary/ErrorBoundary.js, src/components/MapSettings/MapSettings.js, src/components/MobileSettingsHeader/MobileSettingsHeader.js, src/components/SettingsDropdowns/SettingsDropdowns.js, src/components/TabLists/TabLists.js, src/views/UnitView/components/ContactInfo/ContactInfo.js
defaultProps are deprecated in React v18.
Therefore change defaultProps to JS default parameters.
Refs [PL-54](https://helsinkisolutionoffice.atlassian.net/browse/PL-54)
[PL-54]: https://helsinkisolutionoffice.atlassian.net/browse/PL-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: change defaultProps to JS default parameters

browserTests/views/areaTest.js, src/components/DescriptionText/DescriptionText.js, src/components/Lists/PaginatedList/PaginatedList.js, src/views/SearchView/SearchView.js, src/views/UnitView/components/PriceInfo/PriceInfo.js
React hydration failed because the server rendered HTML didn't match the client.
Fixes:
- Use NoSsr-tag to resolve hydration errors in DescriptionText and SearchView-components
- Fix PriceInfo rendering to not use nested Typographies
- Use useEffect hook instead of useLayoutEffect
- Skip flaky district test
Refs [PL-54](https://helsinkisolutionoffice.atlassian.net/browse/PL-54)
[PL-54]: https://helsinkisolutionoffice.atlassian.net/browse/PL-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix hydration errors

src/hsl-icons.css, src/views/MapView/components/TransitStops/TransitStops.js
Fix broken HSL TransitStop icon styles.
Fixes [PL-35](https://helsinkisolutionoffice.atlassian.net/browse/PL-35)
[PL-35]: https://helsinkisolutionoffice.atlassian.net/browse/PL-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(hsl-icons): fix HSL TransitStop icon styles

.env.example, .github/workflows/ci.yml, config/default.js, server/server.js, src/views/MapView/utils/transitFetch.js
Use Helsinki's own digitransit-proxy for DigiTransit queries.
Move api-key behind proxy.
Refs [PL-59](https://helsinkisolutionoffice.atlassian.net/browse/PL-59)
[PL-59]: https://helsinkisolutionoffice.atlassian.net/browse/PL-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(digitransit-api): utilize digitransit-proxy

.env.example, src/views/MapView/components/TransitStops/TransitStopInfo/TransitStopInfo.js, src/views/MapView/components/TransitStops/TransitStops.js, src/views/MapView/components/TransitStops/util/util.js, src/views/MapView/utils/transitFetch.js
Transit stops have different GraphQL-schema in API v2 compared to v1.
Update GraphQL-endpoint url and migrate to the new schema.
Details:
- Update GraphQL-endpoint url to v2
- Use `vehicleMode` instead of `vehicleType`
- Update vehicle type mappings
Refs: [PL-85](https://helsinkisolutionoffice.atlassian.net/browse/PL-85)
[PL-85]: https://helsinkisolutionoffice.atlassian.net/browse/PL-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate to DigiTransit Routing API v2

.github/workflows/analyze-code.yml, sonar-project.properties
Switched to the active SonarQube Cloud action as the previous one was deprecated. Also updated "SonarCloud" to "SonarQube Cloud" to reflect the service's name change.
=> Switch CI to use active SonarQube Cloud action

src/views/AddressView/utils/fetchAdministrativeDistricts.js
Validate that units are actual objects. If not then show warning in console, but keep the app working.
https://helsinkisolutionoffice.atlassian.net/browse/PL-114
=> fix: validate that units are real objects PL-114

src/views/MapView/MapView.js, src/views/MapView/utils/loadingReducerSelector.js
Enable loading indicator for service units search map view.
https://helsinkisolutionoffice.atlassian.net/browse/PL-71
[PL-71]: https://helsinkisolutionoffice.atlassian.net/browse/PL-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: mapView enable loading indicator for service unit search PL-71

src/components/TopBar/TopBar.js
Jos WCAG kriteerin mukaan säätää line height asetusta, niin ylimmän valikon tekstit menee piiloon. 
https://helsinkisolutionoffice.atlassian.net/browse/PL-26
Voi testata esim:
https://dylanb.github.io/bookmarklets.html
tai stylus pluginilla
Ennen:
Korjattu:
=> fix: Accessibility fix line height PL-26

client/client.js, config/default.js, server/server.js
Injecting environment variables was removed in the during Vite migration, bringing the functionality back.
=> fix: inject client env variables correctly Ref: PL-89
